### ISSUE TITLE
Advancement tag error on multiplayer

### ISSUE THREAD

**Issue by Blizzor** [westernat/AdvancementJS#11]
Advancements with # tag as trigger doesn't work on multiplayer

**Comment by Timongcraft** [comment]
Specifically an item inventory trigger with an item tag.

Example criteria:
```js
(criteriaBuilder) => {
  criteriaBuilder.add(
    "myCriteria",
    TRIGGER.hasItems("myMod:myItem")
  );
  criteriaBuilder.add(
    "myCriteria1",
    TRIGGER.hasItems("#myMod:myItemTag")
  );
}
```

Specific environment: Create Live 5 (Modrinth Modpack)
Advancements Config: `\kubejs\server_scripts\advjs_cl5.js` (line 394)

**Comment by westernat** [comment]
Sorry, my computer is broken and I can't fix it for the time being

**Comment by westernat** [comment]
May be you can use `TRIGGER.hasItems(PREDICATE.item(itemPredicate => itemPredicate.setTag('mymod:myTag')))`
