### ISSUE TITLE
Curseforge Support

### ISSUE THREAD

**Issue by Blizzor** [westernat/AdvancementJS#12]
Right now the mod isn't available on curseforge. Can you please add the mod to curseforge?

**Comment by westernat** [comment]
sure



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/08/2024 17:14 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [westernat/AdvancementJS] Curseforge Support (Issue #12) |

Right now the mod isn't available on curseforge. Can you please add the mod to curseforge?
