### ISSUE TITLE
Inventory Change

### ISSUE THREAD

**Issue by wolfieboy09** [westernat/AdvancementJS#13]
I have an item where once the player obtains the item, it gives them an advancement. How do I do that?

**Comment by westernat** [comment]
Here is an example, hope you can understand it
```js
const {TRIGGER} = event;
event.create("advjs:example").criteria(c => {
   c.add("obtain", TRIGGER.hasItems('diamond'))
})
```



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/11/2024 00:27 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [westernat/AdvancementJS] Inventory Change (Issue #13) |

I have an item where once the player obtains the item, it gives them an advancement. How do I do that?

**Comment by wolfieboy09** [comment]
I currently have

```js
AdvJSEvents.advancement(event => {
    const { PREDICATE, TRIGGER } = event;

    const root = event.create("advjs:mekcre")
        .display(displayBuilder => {
            displayBuilder.setTitle("Mekanizing Create")
            displayBuilder.setDescription("Welcome to Mekanizing Create!")
            displayBuilder.setIcon("create:flywheel")
        })
        .criteria(criteriaBuilder => criteriaBuilder.add("iron_oxide", iron_oxide))

    root.addChild('advjs:iron_oxide', build => {
        build.create('advjs:example')
        .display(builder => {
            builder.setTitle('Oxidizing Time')
            builder.setDescription('Obtain Iron Oxide')
            builder.setIcon('kubejs:iron_oxide')
        })
        .criteria(c => { c.add("obtain", TRIGGER.hasItems('kubejs:iron_oxide')) })
    })
})
```
and get the following error:
![image](https://github.com/westernat/AdvancementJS/assets/105564186/e2ca95ec-4d20-4749-8229-584146a404e5)

**Comment by wolfieboy09** [comment]
I see what I did wrong, one second

**Comment by wolfieboy09** [comment]
Yeah I am doing something really wrong

**Comment by westernat** [comment]
have you resoved it?

**Comment by wolfieboy09** [comment]
I still get errors
