### ISSUE TITLE
Cant use .setRecipe

### ISSUE THREAD

**Issue by Zahar2loshara** [westernat/AdvancementJS#14]
When i want to recreate a recipe achievement and use .setRecipe, im cant, gives error, i ask help on kjs support, nope.
So pls make wiki more understandable (and maybe readeble) and fix bug
(If need you can check support ticket [here](https://discord.com/channels/303440391124942858/1239718647107158107)

1.20.1 Fabric

**Comment by westernat** [comment]
there's a trouble with my network,
so paste your code here, please



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/14/2024 20:09 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [westernat/AdvancementJS] Cant use .setRecipe (Issue #14) |

When i want to recreate a recipe achievement and use .setRecipe, im cant, gives error, i ask help on kjs support, nope.
So pls make wiki more understandable (and maybe readeble) and fix bug
(If need you can check support ticket here

1.20.1 Fabric

**Comment by Zahar2loshara** [comment]
`AdvJSEvents.advancement(event => {
  const { CONDITION, PREDICATE, PROVIDER, TRIGGER } = event;
event.create("sfm:comp_dirt")
.criteria(criteriaBuilder => {
criteriaBuilder.add("dirt", 
TRIGGER.hasItems("dirt"));
})
.rewards(rewardsBuilder.setRecipes("kubejs:kjs/sfm_compressed_dirt"));
})`

**Comment by Zahar2loshara** [comment]
Oh and error "[14:09:08] [ERROR] ! fd.js#8: Error in 'AdvJSEvents.advancement': ReferenceError: "rewardsBuilder" is not defined."

**Comment by westernat** [comment]
This is a js syntax error
You should write something like this:
`.rewards(rewardsBuilder => rewardsBuilder.setRecipes("kubejs:kjs/sfm_compressed_dirt"))`

**Comment by Zahar2loshara** [comment]
All works without errors, thank for help!
