### ISSUE TITLE
[Suggestion] Support filters in `remove`

### ISSUE THREAD

**Issue by ExDrill** [westernat/AdvancementJS#8]
Similar to recipes, I believe you should be able to remove advancements based off a set of filters. I think some potentially helpful filters could be:

* Removing advancements by modid or namespace, like being able to remove all vanilla advancements
* Removing advancements by criteria trigger
* Removing advancements and their children, example: removing `minecraft:story/root` will remove all other advancements from the same category.

**Comment by westernat** [comment]
The third point has already supported in vanilla, so I will just implement another two

**Comment by westernat** [comment]
remove filters supported
