### ISSUE TITLE
Suggestion: Advancement display should be optional.

### ISSUE THREAD

**Issue by ExDrill** [westernat/AdvancementJS#9]
Advancement display in vanilla is completely optional, and I believe it should be reflected here. Modpack creators may want to handle advancement display through another mod, different to vanilla's, or just use them for technical purposes.

For example, I'm using the Patchouli mod to create a guide book that has pages unlocked through advancements, and I'd like to mass generate the required advancements through JS.

**Comment by westernat** [comment]
fine, i am already fixed it.
